language: node_js

install: skip
script: skip
addons:
  apt:
    packages:
      - sshpass
      

deploy:
  - provider: azure_web_apps
    verbose: true
    username: rojesh-resume\$rojesh-resume
    password: eeh9kc28ZeKnSGDnnBtvmE4CY5kP4hqsica1iSRYokeljCcGYN5hTlkbbjPB
    slot: resume-rojesh
    site: https://rojesh-resume.azurewebsites.net

    skip_cleanup: true
