language: node_js

install: skip
script: skip
addons:
  apt:
    packages:
      - sshpass
      

deploy:
  - provider: azure_web_apps
    verbose: true
    username: rojesh-resume\$rojesh-resume
    password: 3Sv00DZZTaX0RHdun0Mj1gmGhJk4tT5kbgXwY82pXqSq7hykCySmpbijeDJ2
    slot: 
    site: https://rojesh-resume.azurewebsites.net

    skip_cleanup: true
