language: node_js

install: skip
script: skip

addons:
  apt:
    packages:
      - sshpass

deploy:
  - provider: azure_web_apps
    verbose: true
    username: resume-rojesh\$resume-rojesh
    password: h5RflwlHADbiQlnlu10bGoQ64TND0enzjCAJkefpjmipfs7LzKP1Wpq1YFPT
    slot: resume-rojesh
    site: https://resume-rojesh.azurewebsites.net

    skip_cleanup: true
